{
  description = "sparkbtcbot-skill — Spark Bitcoin L2 wallet skill for AI agents";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      # x86_64-darwin is deliberately absent. nixpkgs unstable now THROWS on
      # it (Intel Mac support was dropped in 26.11), so declaring it does not
      # add coverage — it makes `nix flake check --all-systems` fail outright
      # and gives an Intel-Mac user an evaluation error instead of a clean
      # "unsupported system".
      systems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # ONE SOURCE OF TRUTH. Name and version are read from package.json rather
      # than restated here. A flake that hardcodes them is a second declaration
      # of the same fact, and the two drift the first time someone bumps a
      # version without thinking about Nix — which is exactly the class of bug
      # this package's own CI hardening exists to catch elsewhere.
      pkgJson = builtins.fromJSON (builtins.readFile ./package.json);

      # The dependency closure, read straight from package-lock.json (see the
      # package below for why there is no npmDepsHash). One definition, used by
      # both the package and the unit-test check — two copies of "where the
      # deps come from" is two things that can disagree.
      npmLock = pkgs: {
        npmDeps = pkgs.importNpmLock { npmRoot = ./.; };
        npmConfigHook = pkgs.importNpmLock.npmConfigHook;
      };
    in
    {
      packages = forAllSystems (pkgs: rec {
        default = sparkbtcbot-skill;

        sparkbtcbot-skill = pkgs.buildNpmPackage {
          pname = pkgJson.name;
          inherit (pkgJson) version;

          src = ./.;

          # No npmDepsHash. The dependency closure is read straight from
          # package-lock.json by importNpmLock: every entry there already
          # carries an `integrity` hash, and importNpmLock fetches each tarball
          # as its own fixed-output derivation against that hash. That removes
          # the one fact this flake used to restate — a closure hash that had
          # to be regenerated by hand (with a Nix binary nobody here had) after
          # every lockfile change, and that 0.8.0 shipped stale. Now a lockfile
          # change is the whole update; nothing to paste.
          inherit (npmLock pkgs) npmDeps npmConfigHook;

          # There is no build script in package.json — the package ships the
          # sources it publishes. Nothing to compile, so skip the default
          # `npm run build` that buildNpmPackage would otherwise attempt.
          dontNpmBuild = true;

          nodejs = pkgs.nodejs_22;

          meta = with pkgs.lib; {
            description = pkgJson.description or "Spark Bitcoin L2 wallet skill for AI agents";
            homepage = "https://github.com/echennells/sparkbtcbot";
            license = licenses.mit;
            mainProgram = "sparkbtcbot";
            platforms = systems;
          };
        };
      });

      # TESTS LIVE IN `checks`, NOT IN THE PACKAGE'S checkPhase.
      #
      # `nix flake check` runs these; `nix build` and `nix run` do not. That
      # split is deliberate:
      #
      #   - A flake is a PACKAGING definition. Coupling `nix run` to the test
      #     suite makes every consumer pay for a test run they did not ask for,
      #     and makes packaging a known-imperfect version impossible.
      #   - CI already runs these tests on node 20/22/24. This is a fourth
      #     place they can run, and a fourth place they can disagree — so it
      #     runs the SAME `npm run test:unit` rather than its own invocation,
      #     keeping package.json the single definition of what "the tests" are.
      #
      # What this adds over CI: the Nix sandbox has no network and a pinned
      # toolchain, so a test that quietly depends on either fails here and
      # passes there. Only tests/unit is run — tests/integration and
      # tests/funded need a network and real funds, and would fail in the
      # sandbox for reasons unrelated to correctness.
      checks = forAllSystems (pkgs: {
        unit-tests = pkgs.buildNpmPackage {
          pname = "${pkgJson.name}-unit-tests";
          inherit (pkgJson) version;
          src = ./.;
          inherit (npmLock pkgs) npmDeps npmConfigHook;
          dontNpmBuild = true;
          nodejs = pkgs.nodejs_22;

          # EXPLICIT checkPhase, not `npmTestScript`.
          #
          # buildNpmPackage has no npmTestScript attribute. Setting one is
          # silently ignored — Nix does not reject unknown attrs — so the first
          # version of this check ran NO tests and passed against a
          # deliberately failing one. A check that cannot fail reads as
          # coverage and provides none.
          doCheck = true;
          checkPhase = ''
            runHook preCheck
            npm run test:unit
            runHook postCheck
          '';

          # The check is the point; the output is not. Produce a marker so the
          # derivation has something to install rather than failing on an empty
          # install phase.
          installPhase = ''
            runHook preInstall
            mkdir -p $out
            echo "unit tests passed for ${pkgJson.name} ${pkgJson.version}" > $out/result
            runHook postInstall
          '';
        };
      });

      # A shell for working ON this repo, deliberately minimal: node and npm
      # only. It does NOT pin dependencies — package-lock.json already does
      # that, and a shell that installed its own set would be a third answer to
      # a question package.json and the devcontainer already answer.
      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShell {
          packages = [ pkgs.nodejs_22 ];
          shellHook = ''
            echo "sparkbtcbot-skill dev shell — node $(node --version), npm $(npm --version)"
            echo "deps come from package-lock.json: run 'npm ci'"
          '';
        };
      });
    };
}
